"""many to many association for planning sessions and teachers

Revision ID: 845507976fa6
Revises: e9c1a7b2d4f6
Create Date: 2026-04-16 23:01:51.673268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845507976fa6'
down_revision: Union[str, None] = 'e9c1a7b2d4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_session_teachers',
    sa.Column('planning_session_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['planning_session_id'], ['planning_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('planning_session_id', 'teacher_id')
    )
    op.drop_index('ix_planning_sessions_teacher_id', table_name='planning_sessions')
    op.drop_constraint('uq_planning_session', 'planning_sessions', type_='unique')
    op.create_unique_constraint('uq_planning_session', 'planning_sessions', ['year', 'section', 'speciality', 'semester', 'day', 'time_start', 'type', 'subject', 'group'])
    op.drop_constraint('planning_sessions_teacher_id_fkey', 'planning_sessions', type_='foreignkey')
    op.drop_column('planning_sessions', 'teacher_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planning_sessions', sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('planning_sessions_teacher_id_fkey', 'planning_sessions', 'teachers', ['teacher_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_planning_session', 'planning_sessions', type_='unique')
    op.create_unique_constraint('uq_planning_session', 'planning_sessions', ['year', 'section', 'speciality', 'semester', 'day', 'time_start', 'type', 'subject', 'group', 'teacher_id'])
    op.create_index('ix_planning_sessions_teacher_id', 'planning_sessions', ['teacher_id'], unique=False)
    op.drop_table('planning_session_teachers')
    # ### end Alembic commands ###
