"""align specialized user uniqueness

Revision ID: a835217b156f
Revises: a1c2d3e4f5g6
Create Date: 2026-04-07 14:14:44.607683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a835217b156f'
down_revision: Union[str, None] = 'a1c2d3e4f5g6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_users_user_id_key', 'admin_users', type_='unique')
    op.drop_index('ix_admin_users_user_id', table_name='admin_users')
    op.create_index(op.f('ix_admin_users_user_id'), 'admin_users', ['user_id'], unique=True)
    op.drop_constraint('teacher_users_employee_id_key', 'teacher_users', type_='unique')
    op.drop_constraint('teacher_users_user_id_key', 'teacher_users', type_='unique')
    op.drop_index('ix_teacher_users_user_id', table_name='teacher_users')
    op.create_index(op.f('ix_teacher_users_user_id'), 'teacher_users', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_users_user_id'), table_name='teacher_users')
    op.create_index('ix_teacher_users_user_id', 'teacher_users', ['user_id'], unique=False)
    op.create_unique_constraint('teacher_users_user_id_key', 'teacher_users', ['user_id'])
    op.create_unique_constraint('teacher_users_employee_id_key', 'teacher_users', ['employee_id'])
    op.drop_index(op.f('ix_admin_users_user_id'), table_name='admin_users')
    op.create_index('ix_admin_users_user_id', 'admin_users', ['user_id'], unique=False)
    op.create_unique_constraint('admin_users_user_id_key', 'admin_users', ['user_id'])
    # ### end Alembic commands ###
